version: 1.2.0.{build}

image: Previous Visual Studio 2017

branches:
  except:
    - gh-pages

skip_tags: true

skip_commits:
  message: \[(ci skip|skip ci)\].*

clone_depth: 50

test: off

build_script:
- cmd: dotnet restore
- cmd: dotnet test ./tests/MessagePack.FSharpExtensions.Tests/MessagePack.FSharpExtensions.Tests.fsproj
- cmd: dotnet test ./tests/MessagePack.FSharpExtensions.NET.Tests/MessagePack.FSharpExtensions.NET.Tests.fsproj

